### ISSUE TITLE
Cards should flip

### ISSUE THREAD

**Issue by Wgil** [Wgil/memory-game#2]
Clicking a card should make it flip, animate it and update its `flipped` prop.

**Comment by mmajdanski** [comment]
I've taken a shot at this and created it via CSS. Not sure if it will suffice long-term since I don't know the business logic for what the Back of the Cards is going to be.

**Comment by Wgil** [comment]
It is great to have you here!

Regarding business logic, there is not much done yet. I created [this file](https://github.com/Wgil/memory-game/blob/development/src/minimal_state.json) thinking as a minimal state representation so we can go on from there. At this stage we are very open to create something very simple that works and wen can customize it in the long run. :-)

 Thanks for contribute to the project and happy coding!

**Comment by Wgil** [comment]
@mmajdanski The animation looks great :-) I am going to write the user stories to set clear the business logic. I left some comments in the PR, let me hear if you want to give it a try.

**Comment by Wgil** [comment]
Hey @mmajdanski how is it going buddy? I recommend to don't update your branch with development since you are going to have some conflicts, so don't worry about updating it. I'll take care of the conflicts for you.

**Comment by Wgil** [comment]
@mmajdanski I already merged your changes bro, perhaps you want to checkout this task #20 to set all the styles into the `styled-component` as we talked about. If you have any doubt feel free to task.

**Comment by mmajdanski** [comment]
Hey thanks for merging the changes. I apologize. This weekend turns out to
be a holiday weekend and I was unavailable for the past few days. I'll take
a look today since I am back in town.

**Comment by Wgil** [comment]
Don't worry bro. I didn't work on the project this weekend :)
