### ISSUE TITLE
Improve Card styled component

### ISSUE THREAD

**Issue by Wgil** [Wgil/memory-game#20]
By the time, the `Card` component is using styled-component as well as styles on a separated stylesheet.

The goal of this task is to merge all styles of the Card on the `Container` styled-component definition inside that the `Card.js` component file.

**Comment by mmajdanski** [comment]
I had looked into styled-components a bit now and understand the use case. Very powerful. I'll take this task on. 

Just curious, how did you hear about styled-components or any other best practices? Always interested in learning resources. I use Medium a lot :spades:

**Comment by Wgil** [comment]
I was reading the code of a project and saw this package in action :-) Read other's code is also good to know about practices, patterns, etc. Medium is also great. You can also join these communities https://thedevs.network/
